version: "3"

services:
  flipt:
    image: markphelps/flipt:latest
    ports:
      - "8080:8080"
    networks:
      - backend
    volumes:
      - "./flipt.db:/var/opt/flipt/flipt.db"

  example:
    build: .
    ports:
      - "8000:8000"
    networks:
      - backend
    depends_on:
      - flipt

networks:
  backend:
